#controllers:
#    resource: ../../src/Controller/
#    type: annotation
#
#kernel:
#    resource: ../../src/Kernel.php
#    type: annotation
borrame:
    path: /borrame
    controller: App\Infrastructure\UI\Symfony\Controller\BorrameController
    methods: ['GET']    
