api_platform:
    title: API Platform
    version: 1.0.0
    show_webby: false
    mapping:
        paths:
            - '%kernel.project_dir%/config/mapping/api_platform'
    patch_formats:
        json: [ 'application/merge-patch+json' ]

    formats:
        jsonld:
            mime_types:
                - 'application/ld+json'
        jsonhal:
            mime_types:
                - 'application/hal+json'
        jsonapi:
            mime_types:
                - 'application/vnd.api+json'
        json:
            mime_types:
                - 'application/json'
        xml:
            mime_types:
                - 'application/xml' 
                - 'text/xml'
        yaml:
            mime_types:
                - 'application/x-yaml'
        csv:
            mime_types:
                - 'text/csv'
        html:
            mime_types:
                - 'text/html'
        xlsx:
            mime_types:
                - 'application/vnd.ms-excel'
        
    collection:
        pagination:
            items_per_page: 15
            client_items_per_page: true
            items_per_page_parameter_name: page_size

    exception_to_status:
        Tangram\Domain\Assertion\Exception\AssertException: !php/const Symfony\Component\HttpFoundation\Response::HTTP_UNPROCESSABLE_ENTITY

    swagger:
        versions: [ 3 ]
        api_keys:
            apiKey:
                name: Authorization
                type: header
    # Mercure integration, remove if unwanted
    mercure:
        hub_url: '%env(MERCURE_SUBSCRIBE_URL)%'
