api_platform:
    title: Hello API Platform
    version: 1.0.0
    show_webby: false
    mapping:
        paths:
            - '%kernel.project_dir%/config/mapping/api_platform'
    patch_formats:
        json: [ 'application/merge-patch+json' ]

    collection:
        pagination:
            items_per_page: 10
            client_items_per_page: true
            items_per_page_parameter_name: page_size

    exception_to_status:
        Tangram\Domain\Assertion\Exception\AssertException: !php/const Symfony\Component\HttpFoundation\Response::HTTP_UNPROCESSABLE_ENTITY
    swagger:
        versions: [ 3 ]
        api_keys:
            apiKey:
                name: Authorization
                type: header
    # Mercure integration, remove if unwanted
    mercure:
        hub_url: '%env(MERCURE_SUBSCRIBE_URL)%'
