doctrine:
    dbal:
        types:
            EntryId: App\Infrastructure\Doctrine\DBAL\Type\Vocabulary\EntryIdDBALType
            MeaningId: App\Infrastructure\Doctrine\DBAL\Type\Vocabulary\MeaningIdDBALType
            Deep: App\Infrastructure\Doctrine\DBAL\Type\Vocabulary\DeepDBALType
            EntryType: App\Infrastructure\Doctrine\DBAL\Type\Vocabulary\EntryTypeDBALType
            Lang: App\Infrastructure\Doctrine\DBAL\Type\Vocabulary\LangDBALType
