doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        server_version: '8.0'

        #esto puede ir a un fichero aparte, para poder sobrescribirlo
        types:
            GenreId: App\Infrastructure\Doctrine\DBAL\Type\GenreIdType
            MovieId: App\Infrastructure\Doctrine\DBAL\Type\MovieIdType
            DirectorId: App\Infrastructure\Doctrine\DBAL\Type\DirectorIdType
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/config/mapping/doctrine'
                prefix: 'App\Domain'

                
