App\Infrastructure\Api\FilmArchive\Dto\GenreInput:
    properties:
        name:
            -   NotNull: ~
            -   Length:
                    min: 4
                    max: 10
                    minMessage: 'Genre name must be at least {{ limit }} characters long'
                    maxMessage: 'Genre name cannot be longer than {{ limit }} characters'
