App\Infrastructure\Api\FilmArchive\Dto\GenreInput:
    properties:
        name:
            - NotNull: ~
            - Length:
                min: 4
                max: 6
                minMessage: 'Your first name must be at least {{ limit }} characters long'
                maxMessage: 'Your first name cannot be longer than {{ limit }} characters'
