doctrine:
    dbal:
        types:
            date: Tangram\Doctrine\DBAL\Type\CarbonDateType
            date_immutable: Tangram\Doctrine\DBAL\Type\CarbonDateImmutableType
            datetime: Tangram\Doctrine\DBAL\Type\CarbonDateTimeType
            datetime_immutable: Tangram\Doctrine\DBAL\Type\CarbonDateTimeImmutableType

            time: Tangram\Doctrine\DBAL\Type\CarbonTimeType
            time_immutable: Tangram\Doctrine\DBAL\Type\CarbonTimeImmutableType
    
