parameters:


services:
    Tangram\Infrastructure\ApiPlatform\Core\Swagger\Serializer\SwaggerDecorator:
        decorates: 'api_platform.swagger.normalizer.documentation'
        arguments: [ '@Tangram\Infrastructure\ApiPlatform\Core\Swagger\Serializer\SwaggerDecorator.inner' ]
        autoconfigure: false

    gesdinet.jwtrefreshtoken.refresh_token_manager:
        class: Tangram\Infrastructure\Gesdinet\JWTRefreshTokenBundle\Doctrine\RefreshTokenManager
        public: true
        arguments: [ '@doctrine.orm.default_entity_manager', 'Gesdinet\JWTRefreshTokenBundle\Entity\RefreshToken' ]

    tangram.http_cache.client:
        class: GuzzleHttp\Client
        arguments:
            - { base_uri: '%env(HTTP_CACHE_URL)%' }


    api_platform.http_cache.purger:
        alias: Tangram\Infrastructure\ApiPlatform\Core\HttpCache\RedisPurger


    Tangram\Infrastructure\ApiPlatform\Core\HttpCache\RedisPurger:
        autowire: false
        arguments:
            - '@tangram.http_cache.client'        

    Tangram\Infrastructure\Tactician\:
        resource: '../../../Tactician'
        autowire: true
        autoconfigure: true
        public: false

    Tangram\Infrastructure\Doctrine\:
        resource: '../../../Doctrine'
        autowire: true
        autoconfigure: true
        public: false

#    Tangram\Infrastructure\ApiPlatform\Core\:
#        resource: '../../../ApiPlatform/Core'
#        autowire: true
#        autoconfigure: true
#        public: false

    Tangram\Infrastructure\Api\:
        resource: '../../../Api'
        autowire: true
        autoconfigure: true
        public: false


    Tangram\Domain\Event\EventStore:
        alias: Tangram\Infrastructure\Doctrine\Repository\DoctrineEventStore

    order_filter:
        alias: api_platform.doctrine.orm.order_filter

    order_filter_base:
        alias: Tangram\Infrastructure\Api\Filter\AbstractOrderFilter

    Tangram\Infrastructure\Api\Filter\AbstractOrderFilter:
        abstract: true
        arguments: {
            $managerRegistry: '@doctrine',
            $requestStack: ~,
            $orderParameterName: '%api_platform.collection.order_parameter_name%',
            $logger: '@?logger',
            $nameConverter: '@?api_platform.name_converter'
        }

    TextFilter:
        class: Tangram\Infrastructure\Api\Filter\TextFilter
        arguments: [ '@doctrine', ~, '@?logger' ]
        autowire: true
        autoconfigure: true
        public: false

    FullnameFilter:
        class: Tangram\Infrastructure\Api\Filter\FullNameFilter
        arguments: [ '@doctrine', ~, '@?logger' ]
        autowire: true
        autoconfigure: true
        public: false

    FullnameOrder:
        class: Tangram\Infrastructure\Api\Filter\FullNameOrder
        parent: order_filter_base
        autowire: true
        autoconfigure: true
        public: false        

