version: '3.4'

services:
  client:
    command: "yarn dev"
    
  admin:
    command: "yarn dev"
    
  proxy:      
    environment:
      CLIENT_MAX_BODY_SIZE: 64M
      DOMAINS: "
      ${CLIENT_HOST} => https://${CLIENT_HOST_WWW} #local,
      ${CLIENT_HOST_WWW} -> http://client:3000 #local,            
      ${ADMIN_HOST} -> http://admin:3000 #local,
      ${API_HOST} -> http://api:80 #local
      "
