App\Infrastructure\Api\FilmArchive\Dto\MovieOutput:
    attributes:
        id:
             groups: ['read']

        title:
             groups: ['write', 'read']

        year:
             groups: ['write', 'read']

        genres:
             groups: ['write', 'read']

