App\Infrastructure\Api\FilmArchive\Dto\GenreOutput:
    attributes:
        id:
             groups: ['read']

        name:
             groups: ['write', 'read']

        movies:
             groups: ['write', 'read']

