App\Infrastructure\Api\Music\Dto\MusicGroupOutput:
    attributes:
        id:
            groups: ['music_group:read', 'album:read']
    
        name:
            groups: ['music_group:read', 'album:read']
        
        country:
            groups: ['music_group:read', 'album:read']
        
        albums:
            groups: ['music_group:read']
    
App\Infrastructure\Api\Music\Dto\MusicGroupInput:
    attributes:        
#        id:
#            groups: ['album:write']
        name:
            groups: ['music_group:write']
        country:
            groups: ['music_group:write']
        albums:
            groups: ['music_group:write']
