App\Domain\Music\Song:
    attributes:
        id:
            groups: ['output']
    
        order:
            groups: ['output']
        
        name:
            groups: ['output']
        
        duration:
            groups: ['output']
    
App\Infrastructure\Api\Music\Dto\SongInput:
    attributes:
        order:
            groups: ['input']
        name:
            groups: ['input']
        duration:
            groups: ['input']
