parameters:

services:
    Tangram\ApiPlatform\Core\Swagger\Serializer\SwaggerDecorator:
        decorates: 'api_platform.swagger.normalizer.documentation'
        arguments: [ '@Tangram\ApiPlatform\Core\Swagger\Serializer\SwaggerDecorator.inner' ]
        autoconfigure: false    
    
    api_platform.doctrine.orm.query_extension.filter:
        class: Tangram\ApiPlatform\Core\Bridge\Doctrine\Orm\Extension\FilterExtension
        arguments:
            - '@api_platform.metadata.resource.metadata_factory'
            - '@api_platform.filter_locator'
        tags:
            - {name: 'api_platform.doctrine.orm.query_extension.collection', priority: -16}
        autowire: false
        autoconfigure: false
        public: false
