parameters:

services:
    Tangram\ApiPlatform\Core\Swagger\Serializer\SwaggerDecorator:
        decorates: 'api_platform.swagger.normalizer.documentation'
        arguments: [ '@Tangram\ApiPlatform\Core\Swagger\Serializer\SwaggerDecorator.inner' ]
        autoconfigure: false    
                
    gesdinet.jwtrefreshtoken.refresh_token_manager:
        class: Tangram\Gesdinet\JWTRefreshTokenBundle\Doctrine\RefreshTokenManager
        public: true
        arguments: [ '@doctrine.orm.default_entity_manager', 'Gesdinet\JWTRefreshTokenBundle\Entity\RefreshToken']

    Tangram\Doctrine\:
        resource: '../../../Doctrine'
        autowire: true
        autoconfigure: true
        public: false

    Tangram\Symfony\:
        resource: '../../../Symfony'
        autowire: true
        autoconfigure: true
        public: false

    Tangram\ApiPlatform\Core\Bridge\:        
        resource: '../../../ApiPlatform/Core/Bridge'
        autowire: true
        autoconfigure: true
        public: false        
        
    tangram.api_platform.doctrine.orm.text_filter:
        class: Tangram\ApiPlatform\Core\Bridge\Doctrine\Orm\Filter\TextFilter
        arguments: [ '@doctrine', ~, '@?logger' ]
        autowire: true
        autoconfigure: true
        public: false      
