api_platform:
    # Varnish integration, remove if unwanted
    http_cache:
        invalidation:
            enabled: true
            varnish_urls: [ '%env(HTTP_CACHE_URL)%' ]
        max_age: 0
        shared_max_age: 86400 #60*60*24    
        #        vary: ['Content-Type', 'Authorization', 'Origin']
        vary: [ 'Content-Type',  'Origin' ]
        public: true                
