services:
    #SERVICES
    #movies
    MovieTitleFilter:
        class: App\Infrastructure\Api\FilmArchive\Filter\MovieTitleFilter
        arguments: [ '@doctrine', ~, '@?logger' ]

    MovieTitleOrder:
        class: App\Infrastructure\Api\FilmArchive\Filter\MovieTitleOrder
        parent: 'order_filter_base'



    #FILTERS
    #movies
    movie.title_filter:
        parent: MovieTitleFilter
        arguments: { $properties: { 'title': ~ } }
        tags: [ 'api_platform.filter' ]

    movie.id_order:
        parent: 'order_filter'
        arguments: { $properties: { 'id': ~ } }
        tags: [ 'api_platform.filter' ]

    movie.title_order:
        parent: MovieTitleOrder
        arguments: { $properties: { 'title': ~ } }
        tags: [ 'api_platform.filter' ]

    #genres
    genre.name_filter:
        parent: TextFilter
        arguments: { $properties: { name: ~ } }
        tags: [ 'api_platform.filter' ]

    genre.order:
        parent: 'order_filter'
        arguments: { $properties: { id: ~, name: ~ } }
        tags: [ 'api_platform.filter' ]

    #director
    director.name_filter:
        parent: FullnameFilter
        arguments: { $properties: { name: ~ } }
        tags: [ 'api_platform.filter' ]
        
    director.name_order:
        parent: FullnameOrder
        arguments: { $properties: { name: '~' } }
        tags: [ 'api_platform.filter' ]



    #user
    user.order_filter:
        parent: 'order_filter'
        arguments: { $properties: { email: "asc" } }
        tags: [ 'api_platform.filter' ]
