api_platform:
    resource: .
    type: api_platform
#
authentication_token:
    path: /token
    methods: ['POST']
    
#api_login_check:
#    path: /token
#    methods: ['POST']
    
profile:
    path: /profile
    controller: App\Infrastructure\UI\Controller\ProfileController
    methods: ['GET']    
    
