App\Domain\Example\Contact:
    collectionOperations:
        get:
            filters:
                - 'contact.order_filter'
        post: ~

    attributes:
        input: App\Application\Example\Dto\ContactDto
        output: App\Application\Example\Dto\ContactDto
        normalization_context:
            groups: [ 'read' ]
        denormalization_context:
            groups: [ 'write' ]
                        
