App\Domain\Example\Contact:
    collectionOperations:
        post: ~
        get: ~        
#            filters:
#                - 'user.order_filter'
        
    
    graphql:
        item_query: ~
        collection_query:
#            filters:
#                - 'user.order_filter' 
        delete: ~
        update: ~
        create: ~

    attributes:
        input: App\Application\Example\Dto\ContactDto
        output: App\Application\Example\Dto\ContactDto
        normalization_context:
            groups: [ 'read' ]
        denormalization_context:
            groups: [ 'write' ]
                        
