App\Domain\FilmArchive\Genre:
    collectionOperations:
        get:
            filters: 
                - 'genre.order_filter'
                - 'genre.text_filter'
        post: ~

    properties:
        id:
            identifier: true

    attributes:
        input: App\Infrastructure\Api\FilmArchive\Dto\GenreInput
        output: App\Infrastructure\Api\FilmArchive\Dto\GenreOutput
    normalization_context:
        groups: [ 'read' ]
    denormalization_context:
        groups: [ 'write' ]

