App\Domain\FilmArchive\Movie:
    collectionOperations:
        get:
            filters:
                - 'movie.id_order'
                - 'movie.title_order'
                - 'movie.title_filter'
        post: ~

    properties:
        id:
            identifier: true

    attributes:
        input: App\Infrastructure\Api\FilmArchive\Dto\MovieInput
        output: App\Infrastructure\Api\FilmArchive\Dto\MovieOutput
    normalization_context:
        groups: [ 'read' ]
    denormalization_context:
        groups: [ 'write' ]

