App\Application\Greeting\Dto\GreetingDto:
    shortName: 'Greeting'
    description: 'An entity for example purpouses'
    properties:
        id:
            identifier: true
    attributes:
        normalization_context:
            groups: [ 'read' ]
        denormalization_context:
            groups: [ 'write' ]


App\Domain\User\User:
    collectionOperations:
        get:
            filters:
                - 'user.order_filter'

#        collection_query:       #es necesario para que funcione el filtro con graphql
#            filters:
#                - 'user.order_filter'

    graphql:
        item_query: ~
        collection_query:
            filters:
                - 'user.order_filter' 
        delete: ~
        update: ~
        create: ~

    attributes:
        input: App\Application\User\Dto\UserDto
        output: App\Application\User\Dto\UserDto
        normalization_context:
            groups: [ 'read' ]
        denormalization_context:
            groups: [ 'write' ]
                        
