App\Domain\User\User:
    collectionOperations:
        get:
            filters:
                - 'user.order_filter'
                
    attributes:
        input: App\Application\User\Dto\UserDto
        output: App\Application\User\Dto\UserDto
        normalization_context:
            groups: [ 'read' ]
        denormalization_context:
            groups: [ 'write' ]
                        
