App\Domain\Vocabulary\Entry:
    collectionOperations:
        get:
            filters:
                - 'entry.order_filter'
                - 'entry.text_filter'

            security: 'is_granted("ROLE_ENTRY_READ")'

        post:
            security: 'is_granted("ROLE_ENTRY_CREATE")'

    itemOperations:
        get:
            security: 'is_granted("ROLE_ENTRY_READ")'

        put:
            security: 'is_granted("ROLE_ENTRY_UPDATE")'

        delete:
            security: 'is_granted("ROLE_ENTRY_DELETE")'
    properties:
        id:
            identifier: true

    attributes:
        input: App\Domain\Vocabulary\Input\EntryInput
        output: App\Infrastructure\Api\Vocabulary\Output\EntryOutput

        normalization_context:
            groups: [ 'entry:read' ]
        denormalization_context:
            groups: [ 'entry:write' ]

